def templatePath = 'https://raw.githubusercontent.com/openshift/nodejs-ex/master/openshift/templates/nodejs-mongodb.json' 
def templateName = 'nodejs-mongodb-example' 
openshift.withCluster() {
  openshift.withProject() {
    echo "Using project: ${openshift.project()}"
    pipeline {
      agent {
        node {
          label 'nodejs' 
        }
      }
      options {
        timeout(time: 20, unit: 'MINUTES') 
      }
      stages {
        stage('cleanup') {
          steps {
            openshift.selector("all", [ template : templateName ]).delete() 
            if (openshift.selector("secrets", templateName).exists()) { 
              openshift.selector("secrets", templateName).delete()
            }
          }
        }
        stage('create') {
          steps {
            openshift.newApp(templatePath) 
          }
        }
        stage('build') {
          steps {
            def builds = openshift.selector("bc", templateName).related('builds')
            timeout(5) { 
              builds.untilEach(1) {
                return (it.object().status.phase == "Complete")
              }
            }
          }
        }
        stage('deploy') {
          steps {
            def rm = openshift.selector("dc", templateName).rollout()
            timeout(5) { 
              openshift.selector("dc", templateName).related('pods').untilEach(1) {
                return (it.object().status.phase == "Running")
              }
            }
          }
        }
        stage('tag') {
          steps {
            openshift.tag("${templateName}:latest", "${templateName}-staging:latest") 
          }
        }
      }
    }
  }
}